#!/bin/bash

# Copyright (c) 2021 by Philip Collier, github.com/AB9IL
# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version. There is NO warranty; not even for
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

args="$1 $2"

run_proxied() {
    # operate in proxied mode
    proxychains4 firefox --new-tab $args &
    exit 0
}

run_clear() {
    # operate without proxychains
    firefox --new-tab $args &
    exit 0
}

[ -f "/tmp/proxyflag" ] &&  COMMAND="run_proxied"
[ ! -f "/tmp/proxyflag" ] &&  COMMAND="run_clear"
$COMMAND
